require("config.options")
require("config.keymaps")
require("config.autocmds")
require("plugins.treesitter")
require("config.pack")
require("plugins.colorscheme")
require("plugins.fff")
require("plugins.fyler")
